// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pub/mobile.proto

package com.jeary.proto.model;

public final class MobilePhoneProtos {
  private MobilePhoneProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MobilePhoneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MobilePhone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string brand = 1;</code>
     */
    boolean hasBrand();
    /**
     * <code>required string brand = 1;</code>
     */
    java.lang.String getBrand();
    /**
     * <code>required string brand = 1;</code>
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>required .MobilePhone.Hardware hardware = 2 [default = ram];</code>
     */
    boolean hasHardware();
    /**
     * <code>required .MobilePhone.Hardware hardware = 2 [default = ram];</code>
     */
    com.jeary.proto.model.MobilePhoneProtos.MobilePhone.Hardware getHardware();

    /**
     * <code>repeated string software = 3;</code>
     */
    com.google.protobuf.ProtocolStringList
        getSoftwareList();
    /**
     * <code>repeated string software = 3;</code>
     */
    int getSoftwareCount();
    /**
     * <code>repeated string software = 3;</code>
     */
    java.lang.String getSoftware(int index);
    /**
     * <code>repeated string software = 3;</code>
     */
    com.google.protobuf.ByteString
        getSoftwareBytes(int index);
  }
  /**
   * Protobuf type {@code MobilePhone}
   */
  public static final class MobilePhone extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MobilePhone)
      MobilePhoneOrBuilder {
    // Use MobilePhone.newBuilder() to construct.
    private MobilePhone(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MobilePhone(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MobilePhone defaultInstance;
    public static MobilePhone getDefaultInstance() {
      return defaultInstance;
    }

    public MobilePhone getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MobilePhone(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              brand_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.jeary.proto.model.MobilePhoneProtos.MobilePhone.Hardware value = com.jeary.proto.model.MobilePhoneProtos.MobilePhone.Hardware.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                hardware_ = value;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                software_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              software_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          software_ = software_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jeary.proto.model.MobilePhoneProtos.internal_static_MobilePhone_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jeary.proto.model.MobilePhoneProtos.internal_static_MobilePhone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jeary.proto.model.MobilePhoneProtos.MobilePhone.class, com.jeary.proto.model.MobilePhoneProtos.MobilePhone.Builder.class);
    }

    public static com.google.protobuf.Parser<MobilePhone> PARSER =
        new com.google.protobuf.AbstractParser<MobilePhone>() {
      public MobilePhone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MobilePhone(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MobilePhone> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code MobilePhone.Hardware}
     */
    public enum Hardware
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>rom = 1;</code>
       */
      rom(0, 1),
      /**
       * <code>ram = 2;</code>
       */
      ram(1, 2),
      /**
       * <code>size = 3;</code>
       */
      size(2, 3),
      ;

      /**
       * <code>rom = 1;</code>
       */
      public static final int rom_VALUE = 1;
      /**
       * <code>ram = 2;</code>
       */
      public static final int ram_VALUE = 2;
      /**
       * <code>size = 3;</code>
       */
      public static final int size_VALUE = 3;


      public final int getNumber() { return value; }

      public static Hardware valueOf(int value) {
        switch (value) {
          case 1: return rom;
          case 2: return ram;
          case 3: return size;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Hardware>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Hardware>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Hardware>() {
              public Hardware findValueByNumber(int number) {
                return Hardware.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.jeary.proto.model.MobilePhoneProtos.MobilePhone.getDescriptor().getEnumTypes().get(0);
      }

      private static final Hardware[] VALUES = values();

      public static Hardware valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Hardware(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MobilePhone.Hardware)
    }

    private int bitField0_;
    public static final int BRAND_FIELD_NUMBER = 1;
    private java.lang.Object brand_;
    /**
     * <code>required string brand = 1;</code>
     */
    public boolean hasBrand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string brand = 1;</code>
     */
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          brand_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string brand = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HARDWARE_FIELD_NUMBER = 2;
    private com.jeary.proto.model.MobilePhoneProtos.MobilePhone.Hardware hardware_;
    /**
     * <code>required .MobilePhone.Hardware hardware = 2 [default = ram];</code>
     */
    public boolean hasHardware() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .MobilePhone.Hardware hardware = 2 [default = ram];</code>
     */
    public com.jeary.proto.model.MobilePhoneProtos.MobilePhone.Hardware getHardware() {
      return hardware_;
    }

    public static final int SOFTWARE_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList software_;
    /**
     * <code>repeated string software = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSoftwareList() {
      return software_;
    }
    /**
     * <code>repeated string software = 3;</code>
     */
    public int getSoftwareCount() {
      return software_.size();
    }
    /**
     * <code>repeated string software = 3;</code>
     */
    public java.lang.String getSoftware(int index) {
      return software_.get(index);
    }
    /**
     * <code>repeated string software = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSoftwareBytes(int index) {
      return software_.getByteString(index);
    }

    private void initFields() {
      brand_ = "";
      hardware_ = com.jeary.proto.model.MobilePhoneProtos.MobilePhone.Hardware.ram;
      software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBrand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHardware()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBrandBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, hardware_.getNumber());
      }
      for (int i = 0; i < software_.size(); i++) {
        output.writeBytes(3, software_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBrandBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, hardware_.getNumber());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < software_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(software_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getSoftwareList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jeary.proto.model.MobilePhoneProtos.MobilePhone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jeary.proto.model.MobilePhoneProtos.MobilePhone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jeary.proto.model.MobilePhoneProtos.MobilePhone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jeary.proto.model.MobilePhoneProtos.MobilePhone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jeary.proto.model.MobilePhoneProtos.MobilePhone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jeary.proto.model.MobilePhoneProtos.MobilePhone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jeary.proto.model.MobilePhoneProtos.MobilePhone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jeary.proto.model.MobilePhoneProtos.MobilePhone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jeary.proto.model.MobilePhoneProtos.MobilePhone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jeary.proto.model.MobilePhoneProtos.MobilePhone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jeary.proto.model.MobilePhoneProtos.MobilePhone prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MobilePhone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MobilePhone)
        com.jeary.proto.model.MobilePhoneProtos.MobilePhoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jeary.proto.model.MobilePhoneProtos.internal_static_MobilePhone_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jeary.proto.model.MobilePhoneProtos.internal_static_MobilePhone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jeary.proto.model.MobilePhoneProtos.MobilePhone.class, com.jeary.proto.model.MobilePhoneProtos.MobilePhone.Builder.class);
      }

      // Construct using com.jeary.proto.model.MobilePhoneProtos.MobilePhone.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        brand_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        hardware_ = com.jeary.proto.model.MobilePhoneProtos.MobilePhone.Hardware.ram;
        bitField0_ = (bitField0_ & ~0x00000002);
        software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jeary.proto.model.MobilePhoneProtos.internal_static_MobilePhone_descriptor;
      }

      public com.jeary.proto.model.MobilePhoneProtos.MobilePhone getDefaultInstanceForType() {
        return com.jeary.proto.model.MobilePhoneProtos.MobilePhone.getDefaultInstance();
      }

      public com.jeary.proto.model.MobilePhoneProtos.MobilePhone build() {
        com.jeary.proto.model.MobilePhoneProtos.MobilePhone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jeary.proto.model.MobilePhoneProtos.MobilePhone buildPartial() {
        com.jeary.proto.model.MobilePhoneProtos.MobilePhone result = new com.jeary.proto.model.MobilePhoneProtos.MobilePhone(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.brand_ = brand_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hardware_ = hardware_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          software_ = software_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.software_ = software_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jeary.proto.model.MobilePhoneProtos.MobilePhone) {
          return mergeFrom((com.jeary.proto.model.MobilePhoneProtos.MobilePhone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jeary.proto.model.MobilePhoneProtos.MobilePhone other) {
        if (other == com.jeary.proto.model.MobilePhoneProtos.MobilePhone.getDefaultInstance()) return this;
        if (other.hasBrand()) {
          bitField0_ |= 0x00000001;
          brand_ = other.brand_;
          onChanged();
        }
        if (other.hasHardware()) {
          setHardware(other.getHardware());
        }
        if (!other.software_.isEmpty()) {
          if (software_.isEmpty()) {
            software_ = other.software_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSoftwareIsMutable();
            software_.addAll(other.software_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBrand()) {
          
          return false;
        }
        if (!hasHardware()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jeary.proto.model.MobilePhoneProtos.MobilePhone parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jeary.proto.model.MobilePhoneProtos.MobilePhone) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object brand_ = "";
      /**
       * <code>required string brand = 1;</code>
       */
      public boolean hasBrand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public java.lang.String getBrand() {
        java.lang.Object ref = brand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            brand_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        java.lang.Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public Builder setBrand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public Builder clearBrand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        brand_ = value;
        onChanged();
        return this;
      }

      private com.jeary.proto.model.MobilePhoneProtos.MobilePhone.Hardware hardware_ = com.jeary.proto.model.MobilePhoneProtos.MobilePhone.Hardware.ram;
      /**
       * <code>required .MobilePhone.Hardware hardware = 2 [default = ram];</code>
       */
      public boolean hasHardware() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .MobilePhone.Hardware hardware = 2 [default = ram];</code>
       */
      public com.jeary.proto.model.MobilePhoneProtos.MobilePhone.Hardware getHardware() {
        return hardware_;
      }
      /**
       * <code>required .MobilePhone.Hardware hardware = 2 [default = ram];</code>
       */
      public Builder setHardware(com.jeary.proto.model.MobilePhoneProtos.MobilePhone.Hardware value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        hardware_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .MobilePhone.Hardware hardware = 2 [default = ram];</code>
       */
      public Builder clearHardware() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hardware_ = com.jeary.proto.model.MobilePhoneProtos.MobilePhone.Hardware.ram;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSoftwareIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          software_ = new com.google.protobuf.LazyStringArrayList(software_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSoftwareList() {
        return software_.getUnmodifiableView();
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public int getSoftwareCount() {
        return software_.size();
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public java.lang.String getSoftware(int index) {
        return software_.get(index);
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSoftwareBytes(int index) {
        return software_.getByteString(index);
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public Builder setSoftware(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSoftwareIsMutable();
        software_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public Builder addSoftware(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSoftwareIsMutable();
        software_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public Builder addAllSoftware(
          java.lang.Iterable<java.lang.String> values) {
        ensureSoftwareIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, software_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public Builder clearSoftware() {
        software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public Builder addSoftwareBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSoftwareIsMutable();
        software_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MobilePhone)
    }

    static {
      defaultInstance = new MobilePhone(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MobilePhone)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MobilePhone_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MobilePhone_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020pub/mobile.proto\"\204\001\n\013MobilePhone\022\r\n\005br" +
      "and\030\001 \002(\t\022,\n\010hardware\030\002 \002(\0162\025.MobilePhon" +
      "e.Hardware:\003ram\022\020\n\010software\030\003 \003(\t\"&\n\010Har" +
      "dware\022\007\n\003rom\020\001\022\007\n\003ram\020\002\022\010\n\004size\020\003B*\n\025com" +
      ".jeary.proto.modelB\021MobilePhoneProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MobilePhone_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MobilePhone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MobilePhone_descriptor,
        new java.lang.String[] { "Brand", "Hardware", "Software", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
